icons_format = "{icon}"

[theme]
theme = "modern"

[icons]
icons = "awesome"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(0,80)  |"
short = " $title.str(0,40)  |"

[[block]]
block = "pomodoro"
format = " $icon {$message|} "
notify_cmd = "notifysend '{msg}'"
blocking_cmd = false

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
warning = 15.0
alert = 10.0
interval = 30

[[block]]
block = "cpu"
format = " $icon $utilization ($frequency) "
interval = 5
[[block.click]]
button = "left"
cmd = "wezterm start htop"

[[block]]
block = "memory"
format = " $icon $mem_used  ( $icon_swap $swap_used ) "
warning_mem = 80.0
warning_swap = 50.0
critical_swap = 75.0
[[button.click]]
button = "left"
cmd = "wezterm start htop"

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
format = " $icon IND %a %d/%m %R "
interval = 20
timezone = "Asia/Kolkata"

[[block]]
block = "time"
format = " $icon USA %a %d/%m %R "
interval = 10

[[block]]
block = "battery"
format = " $icon $percentage ($time) "
missing_format = ""
warning = 20
critical = 10
interval = 15
