icons_format = "{icon}" 
# icons_format = "<span font='12'>{icon}</span>" 

[theme]
theme = "modern"

[icons]
icons = "awesome6"

# [[block]]
# block = "focused_window"
# [block.format]
# full = " $title.str(max_w:40)  |"
# short = " $title.str(max_w:20)  |"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
increment = 60
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
warning = 15.0
alert = 10.0
interval = 30

[[block]]
block = "cpu"
format = " $icon $utilization ($frequency) "
interval = 5
[[block.click]]
button = "left"
cmd = "xfce4-terminal --command htop"

[[block]]
block = "memory"
format = " $icon $mem_used  ($icon_swap $swap_used) "
warning_mem = 80.0
warning_swap = 50.0
critical_swap = 75.0
[[button.click]]
button = "left"
cmd = "xfce4-terminal --command htop"

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "keyboard_layout"
# driver = "setxkbmap"
# interval = 20

[[block]]
block = "time"
interval = 20
timezone = "Asia/Kolkata"
format = " $icon IND $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "time"
interval = 20
format = " $icon USA $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = " $icon $percentage ($time) "
missing_format = ""
warning = 20
critical = 10
interval = 15

