[greenclip]
blacklisted_applications = ["Qt Selection Owner for Enpass", "Enpass"]
enable_image_support = true
history_file = "/home/shank/.cache/greenclip.history"
image_cache_directory = "/tmp/greenclip"
max_history_length = 400
max_selection_size_bytes = 0
static_history = ["¯_(ツ)_/¯"]
trim_space_from_selection = true
use_primary_selection_as_input = false
