#!/usr/bin/env bash

set -e

CONFIG="base"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# base.conf.yaml
echo "PROCESSING ${CONFIG}${SUFFIX}"
echo "=============================="
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}"

source $(dirname "$0")/scripts/utils.sh
detect_os
case $OS in
manjaro)
    echo "OS - Manjaro"
    echo "PROCESSING linux${SUFFIX}"
    echo "=============================="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "linux${SUFFIX}" "${@}"
    echo "PROCESSING ${OS}${SUFFIX}"
    echo "=============================="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OS}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot-yay" "${@}"
    ;;
debian)
    echo "OS - Debian"
    echo "PROCESSING linux${SUFFIX}"
    echo "=============================="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "linux${SUFFIX}" "${@}"
    echo "PROCESSING ${OS}${SUFFIX}"
    echo "=============================="
    sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OS}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot-apt" "${@}"
    ;;
ubuntu)
    echo "OS - Ubuntu"
    echo "PROCESSING linux${SUFFIX}"
    echo "=============================="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "linux${SUFFIX}" "${@}"
    echo "PROCESSING ${OS}${SUFFIX}"
    echo "=============================="
    sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OS}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot-apt" "${@}"
    ;;
darwin)
    echo "OS - OSX"
    echo "PROCESSING osx${SUFFIX}"
    echo "=============================="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "osx${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot-brew" "${@}"
    ;;
*)
    echo "unknown distro ID: $ID, not doing anything special"
    ;;
esac
