theme = "everforest_dark"

[editor]
line-number = "relative"
rulers = [100, 120]
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

# dont use this as it overwrite the window keybindings
# [keys.normal.space]
# w = ":write"
