format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$golang\
$java\
$nodejs\
$python\
$rust\
$conda\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

scan_timeout = 500

[battery]

[[battery.display]]
threshold = 20
style = "red"

[[battery.display]]
threshold = 30
style = "yellow"
