#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Shank"
email = "shashanksharma21@gmail.com"

[snapshot]
max-new-file-size = "200MiB"

[template-aliases]
'oneline_log' = '''
label(
  separate(" ",
    if(current_working_copy, "working_copy"),
    if(immutable, "immutable", "mutable"),
    if(conflict, "conflicted"),
  ),
  separate(" ",
    format_short_change_id_with_change_offset(self),
    bookmarks,
    tags,
    working_copies,
    if(empty, empty_commit_marker),
    if(description,
      description.first_line(),
      label(if(empty, "empty"), description_placeholder),
    ),
    surround("(", ")", commit_timestamp(self).ago()),
    surround("<", ">", coalesce(author.name(), author.email())),
  ),
) ++ "\n"
'''


[aliases]
# lg = ["log", "-r", "::@", "-T", "builtin_log_oneline"]
lg = ["log", "-r", "::@", "-T", "oneline_log"]
