"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "shashanksharma21@gmail.com"
name = "Shank"

[snapshot]
max-new-file-size = "200MiB"

[aliases]
lg = ["log", "-r", "::@", "-T", "builtin_log_oneline"]
